### ISSUE TITLE
Add a `stack` accessor?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-exceptions#11]
ie, `stack :: Error -> String`, that just reads the `stack` property. There's no agreed-upon format but [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack) all modern browsers support it, and I'm pretty sure it's always a String.

**Comment by garyb** [comment]
I thought we already had this, but actually it's just used in the `show` instance when available: https://github.com/purescript/purescript-exceptions/blob/60b7562f530d9de62a3004646a2f80732d8795df/src/Control/Monad/Eff/Exception.js#L6-L8

**Comment by hdgarrood** [comment]
Ah ok - come to think of it, perhaps it should be `Error -> Maybe String`, then. There might be a purity issue with this too; it wouldn't surprise me if you could violate some expectation if you wrote a program that changed behaviour based on an error's stack. Although I think access to stack traces is probably useful enough that we needn't worry, and people are probably only going to use them while debugging anyway.

**Comment by paf31** [comment]
:+1:
