### ISSUE TITLE
EXCEPTION row is named err

### ISSUE THREAD

**Issue by leighman** [purescript/purescript-exceptions#19]
This means that types don't unify if you use `Eff (exception :: EXCEPTION | e) a` in your own type signature and use eg. `throw`.

Is there a reason for this, other than length? It seems inconsistent with every other effect row name.

**Comment by garyb** [comment]
I'm surprised we don't have an issue for this already actually, as yeah, it's problematic.

**Comment by garyb** [comment]
@paf31 what do you think about changing this now?

**Comment by paf31** [comment]
Makes sense to me. Didn't it used to be called `exception`?
