### ISSUE TITLE
Add ability to specify Error.name

### ISSUE THREAD

**Issue by zudov** [purescript/purescript-exceptions#30]
Currently, there is an accessor for [Error.name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name) (`name :: Error -> String`). It would be nice to have a helper that allows to create an error with a given name, like `namedError :: String -> String -> Error`.

**Comment by JordanMartinez** [comment]
Not sure if it's absence is intentional, but seems reasonable to me.
