### ISSUE TITLE
What about Error.code ?

### ISSUE THREAD

**Issue by Woody88** [purescript/purescript-exceptions#32]
Hi, 

I've been looking at https://nodejs.org/api/errors.html#errors_error_code recently, and I was wondering if this function should be added or should we have a separate package Purescript package for node's error module.

**Comment by garyb** [comment]
`code` isn't part of the browser API for `Error`, so I think this should be something node-specific, yeah.

**Comment by Woody88** [comment]
Ok, thank you!
